operationMap = {
    # visual operations
    'visual-up':0,
    'visual-down':0,
    'visual-left':0,
    'visual-right':0,
    'visual-forward':0,
    'visual-backward':0,
    'visual-rotate-right':0,
    'visual-rotate-left':0,
    'visual-rotate-up':0,
    'visual-rotate-down':0,
    'visual-roll-right':0,
    'visual-roll-left':0,
    'visual-effect0':0,
    'visual-effect1':0,
    'visual-effect2':0,
    'visual-effect3':0,
    'visual-effect4':0,
    'visual-effect5':0,
    'visual-effect6':0,
    'visual-effect7':0,
    'visual-effect8':0,
    'visual-effect9':0
}
